USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DATA_LINEAGE_WH
  WAREHOUSE_SIZE      = 'XSMALL'
  AUTO_SUSPEND        = 60          -- seconds of idle before auto-suspend
  AUTO_RESUME         = TRUE
  INITIALLY_SUSPENDED = TRUE
  MIN_CLUSTER_COUNT   = 1
  MAX_CLUSTER_COUNT   = 1
  COMMENT             = 'Dedicated warehouse for the data lineage application';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DATA_LINEAGE_ROLE
COMMENT = 'Read-only role for the data lineage application';

CREATE USER IF NOT EXISTS DATA_LINEAGE_USER
PASSWORD             = '<strong_password_here>'
DEFAULT_ROLE         = DATA_LINEAGE_ROLE
DEFAULT_WAREHOUSE    = DATA_LINEAGE_WH
MUST_CHANGE_PASSWORD = FALSE
COMMENT              = 'Service account for data lineage application';

GRANT ROLE DATA_LINEAGE_ROLE TO USER DATA_LINEAGE_USER;

GRANT USAGE   ON WAREHOUSE DATA_LINEAGE_WH TO ROLE DATA_LINEAGE_ROLE;
GRANT MONITOR ON WAREHOUSE DATA_LINEAGE_WH TO ROLE DATA_LINEAGE_ROLE;

-- Granting USAGE on the database and schema to allow the role to access metadata
USE ROLE ACCOUNTADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DATA_LINEAGE_ROLE;

-- Replace <DB_NAME> with the actual database name you want to grant access to
USE ROLE SECURITYADMIN;

-- Database & schema access
GRANT USAGE ON DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;

-- Current objects
GRANT SELECT ON ALL TABLES IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;
GRANT SELECT ON ALL VIEWS  IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;

-- Future objects (auto-granted as they're created)
GRANT USAGE  ON FUTURE SCHEMAS IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;
GRANT SELECT ON FUTURE TABLES  IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;
GRANT SELECT ON FUTURE VIEWS   IN DATABASE <DB_NAME> TO ROLE DATA_LINEAGE_ROLE;


